version: '3.2'
services:
  db:
    container_name: "valintalaskentakoostepalvelu-postgres"
    environment:
      - POSTGRES_PASSWORD="postgres"
    build:
      context: "."
    ports:
      - "5433:5432"
