version: '3.2'
services:
  db:
    container_name: "valintalaskentakoostepalvelu-postgres"
    environment:
      - POSTGRES_USER="oph"
      - POSTGRES_PASSWORD="oph"
    build:
      context: "."
    ports:
      - "5433:5432"
