sudo: required

language: java

jdk:
  - openjdk11

services:
- docker

cache:
  directories:
  - $HOME/.m2

env:
  global:
  # AWS_ACCESS_KEY_ID
  - secure: "me9FCoX+gZeGHmBJKF3J8SKxGPXKcvXtZQO2UCy9wADKbetiMZu8QksETfPh7aZoWdNRK9VWKn7v+zh50lVdzpqLW/qHO6yayCQ95PkQvlKMJMMaxf/26SLYqg21AB6riMRSIQ7huWfg2i9eEFawpo8Cd4MIu1FN9RVysioPokSSQWDkjZW1A5l1kl6lZVNncfAW9ZpKlJVw7RwD77c4StBtMqI8YvXq4Eua7/n4AeXMvzxDwAndOBA60xamw4/MLByCHR4zNaSzNOWH//DGK9AnVD4rAyQN5rz5mI5lDlhxA+Q4zbOKEu0TolYT7fJ+kWA5OubtEda80uagFBFeY+EoIgF0oU+qK/WmYHqRKwgtAxLuAoDA8id38onw/216n2KKCx3aIilZAK5aaz+7v8NJGCBHmmy2zsRDTGdPig2+Bmk8Oozzgn9d8fbgRud4avst9yIrroJC68SOxPwAQevn2GceGaM3/7gtf2rKTdPoII+9RmtirJ57N9IWAg9UBSGAdGYSN1Z1xeDuniVa5u4zn3+Nho24KHYDgWORjsnvOsD+gNs+uNpVSwfxj1M+dd5AgestNUXgTcBTB7MHsrKdf5TJcrhq3PuMeD1P5MHJcnlpb0cob+ObafUJBUAEh/yRxzQ0IGGadiftYplXQrfdl5c0N+Fd6N4WSIjCJBA="
  # AWS_SECRET_ACCESS_KEY
  - secure: "AwcAz0s0+JNfnU3KgxN9ER5/ZgOsEo1Y89ph9KiMI49aFh22+U4C7pelvg5TYfRNYvl/xuS3jxKwMH47IgwKVKRaCAl1tdUpdI9Sz9FxqL52OEX+6SYwm8P9j6Lh67FjM9+36KOsQta7Gh10GUJZ3LDFa9voEHQV3s0Fegk6H6yGagxxoqvnuDsOy3BFeTU0gld24vRaLt4EQONrtpJn2pk5UpLMD6OkD7/5wIukSWnfMaWj36AoPUWVu4zgeeyUTOaT3efIsHGQsWVoDg74f8laIrfFeLVtnYZ7BIKsOHFQCE8JACzDav8f9x3LiftvsnrUPcBr2k4dXSxMMrKc7dFKJmr2EqLRkCWfz/+unm06gnyrzidj4nurSS7v0tz36qLI45hbPM3VzbsQxsXwmU850v0njysbNXnscSKgjh6gdBxcFPZG0X5LvpYpq78Si/0pLqpzzrb3LSa+uv+RgCnq5wYv5fzQlsEPtGIthkQKTLMcF/MITJw7ot4ETlW+xB3LPXcGctt60L/8Qpam1G3wd5u1y9eukleSbK8sqLfdvt/x6/cC9XXbMSvgecNshufBy73s1yswTLhUvuu1fwijaioN0JLQNXICNeBR7BpQeCm0vRsAWSRXSirHQ/qxKRTxMPcWeQlZXAKETdsUxb3fukJ2o2mPvJm6aXmO1o4="

install:
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh
- sudo sh -c "printf '\n%s penaali.hard.ware.fi\n' $(dig +short artifactory.opintopolku.fi|head -n1) >> /etc/hosts"
- export ARTIFACT_NAME="valintalaskentakoostepalvelu"

script:
- mvn clean spotless:check package -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

- mv target/valintalaskentakoostepalvelu-*allinone.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
- cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

- export BASE_IMAGE="baseimage-fatjar-openjdk11:ci-125"
- ./ci-tools/common/pull-image.sh
- ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME

deploy:
- provider: script
  script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
  on:
    all_branches: true
