logging:
  level:
    fi.vm.sade.javautils.nio.cas: warn  # CasClient näyttää tunkevan INFO-entryyn koko responsen joten filtteröidään ne pois

springdoc:
  show-actuator: false
  paths-to-match: /resources/**
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
